services:
  postgres:
    image: postgres:17-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
