name: distr-dev

services:
  postgres:
    image: 'postgres:18.3-alpine3.23'
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: distr
    volumes:
      - 'postgres:/var/lib/postgresql/'
    ports:
      - '5432:5432'
  mailpit:
    image: 'axllent/mailpit:v1.29.5'
    ports:
      - '1025:1025'
      - '8025:8025'
  storage:
    image: 'rustfs/rustfs:1.0.0-alpha.83'
    ports:
      - '127.0.0.1:9000:9000'
      - '127.0.0.1:9001:9001'
    volumes:
      - 'rustfs:/data/'
    environment:
      RUSTFS_ACCESS_KEY: local
      RUSTFS_SECRET_KEY: local

volumes:
  postgres:
  rustfs:
