FROM golang:1.26 AS builder
ARG TARGETOS
ARG TARGETARCH
ARG VERSION
ARG COMMIT

WORKDIR /workspace
COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download

COPY api/ api/
COPY cmd/agent/docker/ cmd/agent/docker/
# doesn't exist (yet?)
# COPY pkg/ pkg/
COPY internal/ internal/
RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} \
  go build -a -o agent \
  -ldflags="-s -w -X github.com/distr-sh/distr/internal/buildconfig.version=${VERSION:-snapshot} -X github.com/distr-sh/distr/internal/buildconfig.commit=${COMMIT}" \
  ./cmd/agent/docker/

FROM docker:29.4.0-alpine3.23
WORKDIR /
COPY --from=builder /workspace/agent .

RUN apk add --no-cache curl

HEALTHCHECK --interval=10s --timeout=5s \
  --start-period=1m --start-interval=10s \
  CMD curl -fsS --max-time 4 http://127.0.0.1:8765 > /dev/null

ENTRYPOINT ["/agent"]
