apiVersion: v2
name: distr
description: The easiest way to distribute enterprise software
keywords:
  - distr
  - software distribution
  - on-prem management
  - docker
  - kubernetes
maintainers:
  - name: Glasskube
    url: https://github.com/glasskube
icon: >-
  https://github.com/distr-sh/distr/raw/refs/heads/main/frontend/ui/public/distr-logo.svg
home: https://distr.sh/docs/
type: application
version: 2.20.1
appVersion: 2.20.1
dependencies:
  - name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 18.x.x
    condition: postgresql.enabled
  - name: rustfs
    repository: https://charts.rustfs.com
    version: 0.1.x
    condition: rustfs.enabled
