# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build Docker Autoheal

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
    paths:
      - 'docker-autoheal/**'
      - '.github/workflows/build-docker-autoheal.yaml'
  pull_request:
    paths:
      - 'docker-autoheal/**'
      - '.github/workflows/build-docker-autoheal.yaml'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Login to GitHub Container Registry (tag only)
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Generate Docker Metadata
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: ghcr.io/distr-sh/distr/docker-autoheal
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
          flavor: |
            latest=false
          labels: |
            org.opencontainers.image.description=Docker Autoheal
            org.opencontainers.image.vendor=Glasskube

      - name: Docker build (push on tag only)
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        id: build-push
        with:
          context: '{{defaultContext}}:docker-autoheal'
          platforms: ${{ startsWith(github.ref, 'refs/tags/') && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          sbom: true
          provenance: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}

      - name: Sign the images with GitHub OIDC Token
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        env:
          DIGEST: ${{ steps.build-push.outputs.digest }}
          TAGS: ${{ steps.meta.outputs.tags }}
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes ${images}
