name: Release Please

on:
  push:
    branches:
      - main
      - v*.*.x
      - v*.*.*-rc.x
  workflow_dispatch:

jobs:
  release-please:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Release Please
        id: release-please
        uses: googleapis/release-please-action@5c625bfb5d1ff62eadeeb3772007f7f66fdcf071 # v4.4.1
        with:
          token: ${{ secrets.GLASSKUBE_BOT_SECRET }}
          target-branch: ${{ github.ref_name }}
