name: Release Please

on:
  push:
    branches:
      - main
      - v*.*.x
      - v*.*.*-rc.x
  workflow_dispatch:

jobs:
  release-please:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Release Please
        id: release-please
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0
        with:
          token: ${{ secrets.GLASSKUBE_BOT_SECRET }}
          target-branch: ${{ github.ref_name }}
